apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-science-pipelines-operator-monitor
  namespace: data-science-pipelines-operator
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      control-plane: controller-manager
