apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../opendatahub-operator/kustomize/base
  - ../opendatahub-operator/kustomize/overlays/opendatahub
  - ../data-science-pipelines-operator/config/base

replacements:
  - source:
      kind: Deployment
      name: kubeflow-operator
      fieldPath: metadata.annotations.cio-target-namespace
    targets:
      - select:
          kind: Service
        fieldPaths:
          - metadata.namespace
      - select:
          kind: ServiceAccount
        fieldPaths:
          - metadata.namespace
      - select:
          kind: Deployment
        fieldPaths:
          - metadata.namespace
      - select:
          kind: ServiceMonitor
        fieldPaths:
          - metadata.namespace
      - select:
          kind: Role
        fieldPaths:
          - metadata.namespace
      - select:
          kind: RoleBinding
        fieldPaths:
          - metadata.namespace
