apiVersion: v1
kind: Service
metadata:
  name: data-science-pipelines-operator
  labels:
    control-plane: controller-manager
spec:
  ports:
    - name: metrics
      port: 8080
  selector:
    control-plane: controller-manager
